### ISSUE TITLE
Node.js API WG Meeting 2015-11-19

### ISSUE THREAD

**Issue by pmuellr** [nodejs/api#11]
**Date/Time**: Thursday, Nov 19, 4pm eastern - [world time](http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+API+WG+Meeting+2015-11-19&iso=20151119T21)

**Doodle** for picking your availability: http://doodle.com/poll/zdcb77922sqq8sca
- note Doodle spans M-F 11/16 - 11/20 and M-F 11/30 - 12/4, avoiding US turkey day

**Agenda and minutes** can be collected in here and copied into this repo later: https://docs.google.com/document/d/1gyz0yaKtOW97bPcXOG2mgzpKy5LxFKWezWSzxc_-YQA/edit?usp=sharing

**Previous minutes:** https://github.com/nodejs/api/blob/master/wg-meetings/2015-10-23.md

**Hangout on air** for active participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYcI7IrAtU4xkIGtK9DgI70NhIemFWx8-d1y2enY-ksZb4UtDg?hl=en

**YouTube movie** for observers and saved recording: http://www.youtube.com/watch?v=3rszjGYpbyM

**Hangout on air** event for more details: https://plus.google.com/events/cv3h505lip7aqvil4n5ri0kl8e8

Agenda discussion can happen in this thread.

(format copied from https://github.com/nodejs/LTS/issues/38)

(instructions for creating [Hangouts On Air](https://github.com/nodejs/node/wiki/Meetings:-Creating-a-Hangouts-On-Air-Event) on the nodejs/node wiki)

**Comment by pmuellr** [comment]
@nodejs/api folks - check the 1st comment  - got the doodle up, for weeks before and after US turkey day, and a GDoc for agenda items

**Comment by obastemur** [comment]
The subject `API` sounds (and it is) wider than what is urgently needed in a short term (IMHO). Indeed `private` API may also benefit from `somewhat breaking` work but bringing other JS engines to `node` internally haven't been an issue (i.e. JXcore / node-ch ..)

If we separate the `private` API discussion aside (which is IMHO very hard to implement with ABI consistency for multi engines + another node.js with multi engines discussion may take years)  the `public` API is much easier to go with. So the native modules wouldn't break and everyone would benefit.

JXcore's `public API` haven't changed (in terms of ABI/API) as it now supports 4 engines. (two v8 versions). Anyone embedding JXcore into a native etc. app may simply update to latest binary and gets the latest and greatest. 

So,
1 - I hope the second meeting focuses on `public API` more. It would not make API work separating from `node.js` entirely.

2 - AFAIK, JXcore's `public API` is the only proven approach available ATM and it works. IMHO a public API work shouldn't take much time. Cons/Pros etc. discuss and decide ?  (Attention: `node-ch` and `JXcore macro` are `private API`!)

**Comment by Qard** [comment]
Looks like Nov 19th is the day so far. Anyone else that has yet to add their name to the doodle?

**Comment by ofrobots** [comment]
I've added my name to the Doodle. The 19th does work for me.

**Comment by pmuellr** [comment]
I'm going to go ahead and schedule the meeting for Thursday, Nov 19, 4pm eastern.  I'll update the initial comment with links the hangout bits.

**Comment by pmuellr** [comment]
@nodejs/api - reminder that the WG call is tomorrow - see first comment of this issue for call info

**Comment by pmuellr** [comment]
@nodejs/api - I've (finally) collected the minutes into a doc and created PR https://github.com/nodejs/api/pull/12 to get them in the repo.

Can someone review/edit/merge?

I'll start working on the follow-up items over the next weeks.

**Comment by pmuellr** [comment]
minutes posted here: https://github.com/nodejs/api/blob/master/wg-meetings/2015-11-19.md
