### ISSUE TITLE
Invitation: Face-to-face to discuss multiple VMs in Node

### ISSUE THREAD

**Issue by jasnell** [nodejs/api#14]
All, I would like to invite members of the Google V8 team, Microsoft Chakra team, @nodejs/ctc and @nodejs/api WG to a sit down face-to-face at IBM's Foster City location to discuss the technical details around supporting multiple JavaScript VMs in Node core. Getting everyone together for a day or two can help us identify and hammer out many of the various details and issues and determine the best way forward. I have created a doodle poll with some suggested dates for getting together. Please let me know what dates would work best. We'd like to get everyone in the same room but I can arrange a remote connection for anyone unable to attend in person.

http://doodle.com/poll/649rfsayknyqxwy2

If any of these days do not work, let me know and I'll add some additional options.

Update: Looks like April 5th-6th is the winner.

Thank you!

**Comment by indutny** [comment]
I won't be able to attend in person (at least, right now it doesn't look like it will be possible), but I am willing to join you remotely.

**Comment by Qard** [comment]
I'll join remotely. I'm not particularly core to the issue, but I'd like to help out as I'm able. 😊

Also, maybe we should have github teams to be able to @ mention V8 and Chakra people. Just a thought.

**Comment by orangemocha** [comment]
I will join remotely as well.

**Comment by jasnell** [comment]
Update: Based on the results of the doodle poll, I'm getting this scheduled for April 5th-6th. I will be sending out formal calendar invites soon.

**Comment by mikeal** [comment]
sign me up.

**Comment by obastemur** [comment]
@jasnell can you also share it on Github?

**Comment by jasnell** [comment]
@obastemur ... not sure I follow? You mean in the main nodejs/node github repo?

**Comment by obastemur** [comment]
@jasnell 

>  I will be sending out formal calendar invites soon.

I mean; If you could send a copy to this thread.

**Comment by jasnell** [comment]
@obastemur ... ah, yes, of course :-)

**Comment by jasnell** [comment]
I have sent out the invitations. The date for the event is April 5 and 6 at IBM's Foster City location (1001 E Hillsdale Ste 400, Foster City, CA). Please RSVP to me. You'll need to RSVP in order to get in.

**Comment by mikeal** [comment]
Do we just RSVP in this thread or is there another ticket or system.

**Comment by jasnell** [comment]
details details ;-) ... RSVP to my email

**Comment by Fishrock123** [comment]
mmmmm I need to double check if I can make that.

**Comment by jasnell** [comment]
Please do but we will have a remote option also. Not everyone is going to
make it in person unfortunately.

**Comment by orangemocha** [comment]
Assuming that if we are attending remotely we don't need to RSVP.

**Comment by magicfish2007** [comment]
Is there any achievement in this meeting?:)

**Comment by mhdawson** [comment]
meeting took closing, see discussion in your other issue

**Comment by mhdawson** [comment]
Link to working doc from meeting https://docs.google.com/document/d/1lTYV31RLQd0Rr8tZUbmH0qy3JRLFwJvAh44uFhffw5c/edit#
