### ISSUE TITLE
Next API WG Meeting

### ISSUE THREAD

**Issue by mhdawson** [nodejs/api#16]
One of the actions from the vm face-to-face was to bring this group up to speed on what was discussed and next steps.  I agreed with Trevor to schedule the meeting. 
# Who

@nodejs/api
# When

Thursday April 21 @ 11 AM EST

Doodle poll (closed)  http://doodle.com/poll/2dsp52h95yuh2ch3C
# Where

link for participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYeCz7oV47m-jWBHlXU4M0F3uO1MIXt0COGLd7TRpPRw3lDV_g?hl=en

For those who just want to watch: http://www.youtube.com/watch?v=B6O3nbvkGHc

Events page: https://plus.google.com/events/cdd094nj844cq8ssn5ut4jdtl8s

Google doc for minutes: https://docs.google.com/document/d/1EJUdX_2hndr6k3E5mWOyrk8R-06iBCd48LRuVNlc2qg/edit
# Agenda
- Stand up 
- Actions from last meeting
- Review  discussion/plan from recent vm neutratlity face to face
- Open issues review

**Comment by stefanmb** [comment]
@mhdawson I've completed the poll but some of the times overlap https://github.com/nodejs/node/issues/5779, in the event of a conflict I will give priority to the onboarding.

**Comment by Fishrock123** [comment]
cc also @kobalicek from https://github.com/nodejs/roadmap/issues/54#issuecomment-207885711

**Comment by jeisinger** [comment]
Feel free to ignore me if it makes scheduling easier (as long as Ali can attend)

**Comment by pmuellr** [comment]
@mhdawson Can we arrange to record this via HOA?  I don't need to attend live, but would like to watch later.  Instructions here: https://github.com/nodejs/node/wiki/Meetings:-Creating-a-Hangouts-On-Air-Event 

I can set this up, if you want

**Comment by mhdawson** [comment]
@pmuellr was planning HOA and know/have done it before.  The one thing I don't know if/how to do is to schedule it so that it shows up in the node.js channel as opposed to my own. Either way we'll record.

**Comment by pmuellr** [comment]
plan on the nodejs channel - see https://github.com/nodejs/TSC/issues/68 ; I don't believe I have access to this yet.  Your own channel is fine tho, if that's the only choice.

**Comment by mhdawson** [comment]
#pmuellr I believe I would have access but don't know how to take advantage of it yet.

**Comment by mhdawson** [comment]
Looks like everybody except for one person who responded can make Thu 21 at 11 AM EST.  Will set that as the time.

**Comment by mhdawson** [comment]
@nodejs/api - ok meeting set

**Comment by trevnorris** [comment]
Not sure I'll be able to attend. Can we make sure it's recorded so I can listen in later?

**Comment by mhdawson** [comment]
@trevnorris sorry to hear that, plan to record through hangouts on air.

**Comment by ofrobots** [comment]
I sincerely apologize for missing the meeting. I had forgotten to add a calendar entry for this. I will review the notes and the recording.

**Comment by mhdawson** [comment]
PR for meeting minutes: https://github.com/nodejs/api/pull/19

youtube video is here:  http://www.youtube.com/watch?v=B6O3nbvkGHc (still need to figure out how move to Node.js channel so may change)
