### ISSUE TITLE
Is this the Addon API working group?

### ISSUE THREAD

**Issue by williamkapke** [nodejs/api#18]
Is this the new "home" for the Addon API working group? 

https://nodejs.org/en/about/working-groups/ links it to https://github.com/nodejs/nan

**Comment by mhdawson** [comment]
I think the answer is no, nan was considered separate at the time as it uses a different approach than what was being discussed in the API working group.  Once aspect of what the API working group has discussed (api for add-on mouldes) does overlap but other aspects are not covered by the charter outlined for nan.  So there is some overlap but this was intended to be a different group with a broader focus than nan

**Comment by williamkapke** [comment]
:) Glad I asked!

Maybe this group can take on a task to work with the Addon API to work out the messaging around this to outsiders. Also, the docs outline a path for one group to take over role(s) from another group if that applies here.

Thanks!

**Comment by mhdawson** [comment]
I took the action to review the README.md in the API repo to see if we can make it explain the the relationship better as a starting point.

**Comment by mhdawson** [comment]
Still have not done this, but have not forgotten either :)

**Comment by mhdawson** [comment]
PR created here: https://github.com/nodejs/api/pull/27

**Comment by williamkapke** [comment]
Awesome! I'll just close this issue then.
