### ISSUE TITLE
Platform-agnostic API example

### ISSUE THREAD

**Issue by jjrv** [nodejs/api#32]
[nbind](https://github.com/charto/nbind#readme) is a C++ template based bindings generator with an API designed around C++ standard library types. That way it avoids JavaScript engine details and already the same code can be compiled to native Node.js addons and asm.js code that can be imported using Node.js `require` or inside a browser with most loaders.

The next planned step is to serialize function arguments in a common binary format and compile the addon to a `.so`, `.dll` or `.dylib` so it can provide a stable ABI within a single platform (all versions of Node.js and Electron). Emscripten's embind uses a similar serialization approach that works in practice.

nbind also generates TypeScript definitions from the C++ code and has tools for managing `binding.gyp` files. An addon looks for example like:

```C++
class VectorTest {
public:

  static std::vector<int> getInts() {
    std::vector<int> a {{ 13, 21, 34 }};
    return(a);
  }
};

NBIND_CLASS(VectorTest) {
    method(getInts);
}
```

For example there's a [RisingStack tutorial](https://blog.risingstack.com/writing-native-node-js-modules/) for Node.js addons using NAN, and you can compare its example to an [nbind-based version](https://github.com/peteyy/native-addon-example/issues/1).

I'm really interested to see what others are coming up with. nbind is one possible way to provide a stable ABI (in the future) across all Node.js versions, and a stable API (already today) across all JavaScript implementations on all platforms in general.

**Comment by jjrv** [comment]
Some questions that nbind standardizes are:

- Type coercion and whether `null` is allowed, is toggled using [policies](https://github.com/charto/nbind#type-conversion).
- Bindings can be freely scattered across any number of C++ source files, so adding and removing files from `binding.gyp` will add and remove classes and functions from the addon, no other configuration needed.
- Class instances can be passed by value between the languages, retaining a meaningful type. A C++ class can define a `toJS` method which receives the JavaScript constructor as a callback, and a JavaScript prototype can have a `fromJS` function which receives the C++ constructor as a callback. The callbacks can be used to construct an equivalent object in the other language, implementing methods in that language for the highest possible speed.
- 64-bit integers are handled using the above mechanism, so `int64_t` and `uint64_t` are easy to bind to any JavaScript bignum package (if not, nbind will use the usual number type that only reliably fits 53 bits).

**Comment by mhdawson** [comment]
Existing Node.js community ABI effort is here: https://github.com/nodejs/abi-stable-node.  

There is also work on an FFI level integration separately being done by @mathewloring for which there should be more info soon.   I'll have to look more closely but it seems like nbind is more closely aligned with FFI.

**Comment by jjrv** [comment]
I've left a comment there also and will try to attend the meeting on Friday. nbind is a replacement for NAN that eliminates all V8-specific code, replacing V8 types with C++ standard library types. That also makes it portable to non-V8 platforms like asm.js. Behind the scenes, it uses NAN to accomplish this on Node.js, and custom embind-like code on asm.js.

nbind could be extended to use pretty much any API for the lower level communication between languages: NAPI, FFI... Java and Objective C bridges are also possible, for interfacing React Native with C++ code, for example.

Please see https://github.com/nodejs/abi-stable-node/issues/24

**Comment by mhdawson** [comment]
I think we discussed in the meeting last Friday, so closing but if it should remain open please re-open or let me know and I'll re-open
