### ISSUE TITLE
Initial Javascript API definitions

### ISSUE THREAD

**Issue by obastemur** [nodejs/api#5]
One of the important parts for Node.js API will be the JavaScript engine interface. Before putting up an initial document for it, what necessary steps should be taken?

The questions I have;
- Solid C API ?
- What is the preferred naming for the methods?
- More questions ?

**Comment by trevnorris** [comment]
I've already been working on the JS API initial documentation. Actually started planning it long before this WG was conceived.

It was meant to be done last week, but other events have proven to be more urgent. Regardless, the architecture overview document will be done this coming week.

**Comment by obastemur** [comment]
> I've already been working on the JS API initial documentation. Actually started planning it long before this WG was conceived.

It could be really nice to have a list of TODO items.

**Comment by trevnorris** [comment]
I've landed the general outline of JS API in 973e9cc6b.

**Comment by trevnorris** [comment]
Next will be creating an API outline of individual subsystems (e.g. fs, tcp, etc.).

**Comment by obastemur** [comment]
> Next will be creating an API outline of individual subsystems (e.g. fs, tcp, etc.).

If you can put a template / sample for one of them, I will try do my best to help for the rest.

**Comment by trevnorris** [comment]
@obastemur Thank you much. I'll let you know once I have a template ready.

**Comment by autoit4you** [comment]
So, how low-level is the JS API supposed to be? Similar to the current one? Or on a different level?

**Comment by trevnorris** [comment]
@autoit4you different approach. There will be no stream or event emitter. but not so low as libuv. that would become burdensome in JS. so guess you could say as low as is practical. the current js doc outlines a few things that will be global across the entire JS API. I think that will give some context to what I mean.

**Comment by No9** [comment]
Hi @trevnorris 
Thanks for being front and centre tonight.
Is there an update on the template you mention above?

**Comment by magicfish2007** [comment]
This issue is talking about JS api, not JS native api, am I right? :)
