### ISSUE TITLE
Use cases for Node.js API

### ISSUE THREAD

**Issue by obastemur** [nodejs/api#6]
AFAIK the initial coverage of the API is native C, C++ addon. What is the expectation for using this API internally ?

**Comment by trevnorris** [comment]
So far, none that I know of. Though this should be reassessed as the interface for modules is flushed out.

**Comment by trevnorris** [comment]
I believe usage of the public API internally may come in handy with cases like `Buffer::Data()`. Though it is always up to the discretion of the implementer on what works best.

**Comment by mhdawson** [comment]
From the f-to-f the decision was to push forward on the module API without assuming that it was going to be used internally by Noje.js and just that keep that as a future possibility.

**Comment by jasnell** [comment]
Yep, the immediate goal identified at the VM summit was that before we can begin working on the internal improvements necessary to support multiple vms, etc, we needed to have a better way of shielding the module ecosystem from the internals... which means a better abstraction API. If we get that correct, then there's a possibility we could use it internally but that should be a secondary goal at this point.
