### ISSUE TITLE
Establish a meeting

### ISSUE THREAD

**Issue by cjihrig** [nodejs/api#8]
The concepts behind this group seemed to be well received at the collaborator summit. I'm not sure if this group has enough members yet, but maybe setting up a meeting would help it start moving along, even if it was only once a month.

**Comment by obastemur** [comment]
:+1:

**Comment by Qard** [comment]
Count me in. :smile:

**Comment by mhdawson** [comment]
Me too

**Comment by autoit4you** [comment]
And me

**Comment by No9** [comment]
I'm interested too even as a lurker.

**Comment by JCMais** [comment]
:+1:

**Comment by stefanmb** [comment]
Hi, I am also interested in these meetings.

**Comment by Qard** [comment]
![and my axe](http://cdn.meme.am/instances/400x/15409427.jpg)

**Comment by orangemocha** [comment]
+1

**Comment by robpaveza** [comment]
I'd be interested in being part of that as well.

**Comment by trevnorris** [comment]
Can we make a meeting rule of no bikeshedding of APIs allowed? ;-)

**Comment by Fishrock123** [comment]
I'd also like to attend.

**Comment by pmuellr** [comment]
also interested

I'll offer to set up the Hangouts on Air, since I now know how to do that, if someone else wants to pick a date, create an invite, set initial agenda, etc.  Here's an example of how we "organized" the last tracing-wg meeting: https://github.com/nodejs/tracing-wg/issues/21

**Comment by No9** [comment]
@pmuellr LGTM 
@trevnorris just call a time then and we will see what sticks?

**Comment by pmuellr** [comment]
Should also mention the tracing-wg is trying out doodle for picking dates/times for meetings.  Here's the doodle for the next tracing-wg meeting: http://doodle.com/poll/zwk6c8exh8cn92rn .  To create a new one, click the "schedule an event" link at the top.

**Comment by rvagg** [comment]
and don't forget to click on the option to make it adaptive to people's timezones please!

**Comment by trevnorris** [comment]
Just filled it out. I'll be on a plane Monday, but available the rest of the week.

**Comment by robpaveza** [comment]
Am I mis-reading, or do we not actually yet have a Doodle being worked on? Isn't the one above for tracing-wg?

**Comment by stefanmb** [comment]
@trevnorris @robpaveza I think Rob's reading is correct, the link given was just an example of what the Tracing group is doing. To get things moving I created another poll with similar options to the tracing-wg one. Let's see if we can get something going for next week, if that's insufficient advance notice I can move it to the week after. Here is the link:

http://doodle.com/poll/x9rh4bqtqns87hu9

@rvagg Any help with Hangouts on Air is greatly appreciated, I don't have any experience with it.

**Comment by pmuellr** [comment]
If for some reason @rvagg is busy, I'm happy to help out with the HoA.

On Fri, Oct 2, 2015 at 2:07 PM, Stefan Budeanu notifications@github.com
wrote:

> @trevnorris https://github.com/trevnorris @robpaveza
> https://github.com/robpaveza I think Rob's reading is correct, the link
> given was just an example of what the Tracing group is doing. To get things
> moving I created another poll with similar options to the tracing-wg one.
> Let's see if we can get something going for next week, if that's
> insufficient advance notice I can move it to the week after. Here is the
> link:
> 
> http://doodle.com/poll/x9rh4bqtqns87hu9
> 
> @rvagg https://github.com/rvagg Any help with Hangouts on Air is
> greatly appreciated, I don't have any experience with it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodejs/api/issues/8#issuecomment-145108732.

## 

Patrick Mueller
http://muellerware.org

**Comment by rvagg** [comment]
https://github.com/iojs/io.js/wiki/Meetings:-Creating-a-Hangouts-On-Air-Event

Sorry, I can't organise this, too much of a risk for this WG if I'm an essential for getting progress. Would love @pmuellr to take it on if he can justify the time commitment. I want to be involved because this is such an important part of the future picture of Node so I'll try and join meetings.

**Comment by orangemocha** [comment]
@stefanmb : I think it would be better to give a bit more advance notice.

**Comment by pmuellr** [comment]
@stefanmb another problem is that the current popular date/time is Wed 7, 1pm eastern, which unfortunately is the scheduled time for the [next tracing-wg meeting](https://github.com/nodejs/tracing-wg/issues/24).  The next best date/times only had positives for 4/6 attendees.

Should we do another doodle, for week of Oct 12?

**Comment by stefanmb** [comment]
@orangemocha @pmuellr You are right, I was much too aggressive with the schedule and it also conflicts with the other meeting. 

I’ve closed the existing poll and opened a new one: http://doodle.com/poll/24kdu3ywy68ubpew

I’ve chosen the week of October 19th, my rationale being:
(1) Monday, October 12th is a statutory holiday in US/Canada, which may reduce many participants’ choices right from the start.
(2) Two weeks of advance notice should give more time to get a larger number of participants and also establish an agenda.

Hopefully this attempt works out better!

**Comment by orangemocha** [comment]
@stefanmb : thank you :+1:

**Comment by stefanmb** [comment]
I've closed the poll and selected the top choice: **Friday 10/23/15 4:00 PM EST**
Any input for an agenda or issues you'd like to talk about is welcome. Otherwise I'll come up with a list.
Thanks!

**Comment by pmuellr** [comment]
I've created all the bits for the meeting, linked to in issue https://github.com/nodejs/api/issues/9

There are currently only 3 members of the nodejs/api team:
- cjihrig
- rvagg
- trevnorris

Everyone else should go to the team page - https://github.com/orgs/nodejs/teams/api - and request membership to the team.  That way you'll get all the @nodejs/api team mentions.

**Comment by Fishrock123** [comment]
@pmuellr Done.

**Comment by autoit4you** [comment]
@pmuellr Non-owners/non-collaborators can't access that page and thus won't be able to request membership.

**Comment by pmuellr** [comment]
In case you missed it, but are watching here, there is a  Node.js API WG meeting today at 4pm eastern - https://github.com/nodejs/api/issues/9

cc'ing @nodejs/api for good measure, as well

**Comment by mhdawson** [comment]
Closing this since have set up meetings
