### ISSUE TITLE
API WG Meeting 2015-10-23

### ISSUE THREAD

**Issue by pmuellr** [nodejs/api#9]
**Date/Time**: Wed, 2015-10-23, 1PM pacific - [world time](http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+API+WG+Meeting+2015-10-23&iso=20151023T20)

**Agenda and minutes** can be collected in here and copied into this repo later:
https://docs.google.com/document/d/1KgWQsUUeUbo8ip4G6q5Qaxo4sqYMxL8UJZ1CM231Wds/edit?usp=sharing

**Previous minutes:** none?

**Hangout on air** for active participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYfRZEnX97TP3o2X3GG1LodWHmIy9EdVspVSbRWh34pHHV18eA?hl=en

**YouTube movie** for observers and saved recording: http://www.youtube.com/watch?v=fHU4L6Cl90M

**Hangout on air** event for more details: https://plus.google.com/events/cptau2lkifq0earrgidrmj623p4

Agenda discussion can happen in this thread.

(format copied from https://github.com/nodejs/LTS/issues/38)

(instructions for creating [Hangouts On Air](https://github.com/nodejs/node/wiki/Meetings:-Creating-a-Hangouts-On-Air-Event) on the nodejs/node wiki)

**Comment by pmuellr** [comment]
@nodejs/api - API team - I've created this issue as an invite for the meeting this Friday; the first comment contains all the relevant details.

Agenda items can be discussed here, but should be placed in the **Agenda and Meetings** google doc linked to above.  At the time of the hangout, lick the **Hangout on air** link to join the hangout.

**Comment by Fishrock123** [comment]
:+1:

**Comment by obastemur** [comment]
Great!

**Comment by stefanmb** [comment]
@pmuellr I've updated the Google Docs with a rough initial agenda. Any feedback and further additions would be great! I can also volunteer to do the meeting minutes.

**Comment by pmuellr** [comment]
Thanks for offering!  For other WG's, some folks have contributed notes, and I've scribbled some things down, but generally I plan on watching the YouTube movie and making notes from that.  A day or so after. You can watch at 1.5x (or more) speed, pause, etc.

**Comment by JCMais** [comment]
Would be great to discuss, if possible, about the future of the use of gyp to compile native addons, as initially discussed here https://github.com/nodejs/node/issues/133

**Comment by pmuellr** [comment]
Reminder that the Node.js API WG meeting is today at 4pm eastern - see the first comment of this issue for details

**Comment by stefanmb** [comment]
@pmuellr As discussed I took some minutes here: https://goo.gl/fMcETz

**Comment by pmuellr** [comment]
@node/api & friends:

I've created a `wg-meetings` directory in the repo, and added a meeting doc for this meeting:

https://github.com/nodejs/api/blob/master/wg-meetings/2015-10-23.md

Please feel free to update anything there; some of the text was copy/pasted from GDoc to text editor, may be a few issues.

**Comment by pmuellr** [comment]
I've created issue #11 - Node.js API WG Meeting 2015-11-XX - for the next meeting; I'll fill it out over the rest of this week

**Comment by pmuellr** [comment]
last reminder to work on next meeting bits in issue https://github.com/nodejs/api/issues/11 ; get yourself added to the "api" team at nodejs to get various notices dropped in issues via GH notifications
